eureka:
  client:
    serviceUrl:
      defaultZone: http://zira-eureka/eureka/
mybatis:
  typeAliasesPackage: com.example.zirauser.**.entity
  mapperLocations: classpath:mapper/*.xml
server:
  port: 80
spring:
  application:
    name: zira-user
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://mysql:3306/user?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: root
