eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  typeAliasesPackage: com.example.zirauser.**.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8763
spring:
  application:
    name: zira-user
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: root